---@type conform.FileFormatterConfig
return {
  meta = {
    url = "https://github.com/thlorenz/doctoc",
    description = "📜 Generates table of contents for markdown files inside local git repository. Links are compatible with anchors generated by github or other sites.",
  },
  command = "doctoc",
  stdin = false,
  args = {
    "$FILENAME",
  },
}
