name: Sync Fork with Upstream

on:
    schedule:
        - cron: '0 0 * * *'  # Daily at midnight UTC
    workflow_dispatch:  # Manual trigger

jobs:
    sync:
        uses: georgeharker/sync-fork-reusable/.github/workflows/sync-fork-reusable.yml@main
        with:
            target-branch: 'main'
            source-branch: 'master'
            use-rebase: true
            upstream-repo: "stevearc/conform.nvim"
        secrets:
            gh-token: ${{ secrets.GITHUB_TOKEN }}
